### ISSUE TITLE
The command "node top" occurred something wrong.

### ISSUE THREAD

**Issue by SamLinBIT** [caryll/ideohint-template#1]
This is what occurred in my powershell.

```
PS C:\Users\SamLIN\ideohint-template> npm install
PS C:\Users\SamLIN\ideohint-template> node top
C:\Users\SamLIN\ideohint-template\top.js:23
async function hr() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```
I follow the whole README, and stick here. I don't know what should I do to figure it out.
Oh, I can't understand that `To enable support for CFF OTF input, you need TTX in AFDKO either.` means for.
Can you help me?
Thanks.

**Comment by be5invis** [comment]
Upgrade to Node 8

发自我的 iPhone

**Comment by be5invis** [comment]
Added notes about Node version. version 8.5 or above is **required**.
